"""empty message

Revision ID: 18c72c99d88a
Revises: 75575f3dc6b1
Create Date: 2023-06-26 13:44:00.997665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c72c99d88a'
down_revision = '75575f3dc6b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_answers', sa.Column('telephone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_answers', 'telephone')
    # ### end Alembic commands ###
