"""empty message

Revision ID: 75575f3dc6b1
Revises: 3cb07de4421d
Create Date: 2023-06-26 13:38:48.173848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75575f3dc6b1'
down_revision = '3cb07de4421d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telephone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_notify', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_notify')
    op.drop_column('users', 'telephone')
    # ### end Alembic commands ###
