"""empty message

Revision ID: 8529958417af
Revises: 1cfac0cfdaa0
Create Date: 2023-06-17 20:31:53.341591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8529958417af'
down_revision = '1cfac0cfdaa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bfl_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('insolvent_situation', sa.String(), nullable=True),
    sa.Column('amount_expense', sa.String(), nullable=True),
    sa.Column('guarantees', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('business_info', sa.String(), nullable=True),
    sa.Column('amount_clients', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('amount_deals', sa.String(), nullable=True),
    sa.Column('amount_expense', sa.String(), nullable=True),
    sa.Column('guarantees', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner_answers')
    op.drop_table('lead_answers')
    op.drop_table('bfl_answers')
    # ### end Alembic commands ###
